# run_script2.yml
- name: Run chris_time_aware_bias_detection
  hosts: localhost
  tasks:


    - name: Check Linux distribution
      ansible.builtin.raw: cat /etc/os-release
      register: os_info

    - name: Print OS information
      debug:
        var: os_info.stdout_lines

    - name: Install packages on Alpine
      ansible.builtin.raw: |
        apk update && apk add build-base gcc g++ python3-dev
      become: true
  
    - name: Install required Python packages
      ansible.builtin.pip:
        name:
          - vaderSentiment
          - nltk
          - pandas
          - matplotlib
          - seaborn
        executable: pip3
  
    - name: Run chris_time_aware_bias_detection
      ansible.builtin.command: python3 ./scripts/chris_time_aware_bias_detection.py
