# run_script2.yml
- name: Run chris_time_aware_bias_detection
  hosts: localhost
  tasks:
  
    - name: Install required Python packages
      ansible.builtin.pip:
        name:
          - build-essential
          - python3-dev
          - gcc
          - g++
          - vaderSentiment
          - nltk
          - pandas
          - matplotlib
          - seaborn
        executable: pip3
  
    - name: Run chris_time_aware_bias_detection
      ansible.builtin.command: python3 ./scripts/chris_time_aware_bias_detection.py
