# run_script2.yml
- name: Run chris_time_aware_bias_detection
  hosts: localhost
  tasks:

    - name: Install build tools on Debian/Ubuntu
      ansible.builtin.raw: |
        apt update && apt install -y build-essential python3-dev

    - name: Check Linux distribution
      ansible.builtin.raw: cat /etc/os-release
      register: os_info

    - name: Print OS information
      debug:
        var: os_info.stdout_lines

    # - name: Install packages on Alpine
    #   community.general.apk:
    #     name:
    #       - build-essential
    #       - python3-dev
    #       - gcc
    #       - g++
    #       - libffi-dev
    #       - libssl-dev
    #     state: present
  
    - name: Install required Python packages
      ansible.builtin.pip:
        name:
          - vaderSentiment
          - nltk
          - pandas
          - matplotlib
          - seaborn
        executable: pip3
  
    - name: Run chris_time_aware_bias_detection
      ansible.builtin.command: python3 ./scripts/chris_time_aware_bias_detection.py
